// Package media issues upload targets for the media library.
//
// Two backends are supported, chosen by configuration:
//
//	chisimba (default) — the device uploads through Chisimba's own file API.
//	  The upload URL is just the gateway's /api/v1/files endpoint. The media
//	  record is created by field-service on the next sync pull, once the file
//	  has landed in Chisimba's storage.
//
//	s3 (optional) — the device uploads directly to an S3-compatible object
//	  store via presigned URL. This is the right choice for large libraries
//	  or multi-reserve deployments where uploads should not sit behind the
//	  web gateway.
//
// The package exists to keep that choice out of the HTTP layer: the handler
// asks for a target and gets one, without knowing which backend answered.
package media

import (
	"context"
	"errors"
	"fmt"
	"time"
)

// ErrNotConfigured is returned by a backend that has not been set up. It is
// distinct from a storage fault: a missing bucket name is an operator
// mistake, not a device mistake, and the client is told so.
var ErrNotConfigured = errors.New("media: backend not configured")

// Target is where a device should PUT its media.
type Target struct {
	// URL is the absolute URL the device uploads to. For the chisimba
	// backend this is the gateway endpoint; for s3 it is a presigned URL.
	URL string `json:"url"`

	// Method is the HTTP verb the device should use. POST for Chisimba
	// (multipart form), PUT for S3 (raw object body).
	Method string `json:"method"`

	// ExpiresAt is when the target stops being valid, RFC3339. For the
	// chisimba backend this is far in the future — the gateway endpoint
	// does not expire, so the value is informational only. For s3 it is
	// real: the presigned URL stops working after this moment.
	ExpiresAt string `json:"expires_at"`

	// MediaID is the identifier the sync protocol will use to confirm the
	// upload. For both backends it is generated by field-service, not by
	// the client, so the id can double as the object key.
	MediaID string `json:"media_id"`

	// Backend names which one answered: "chisimba" or "s3". A device that
	// has different upload paths for the two uses this to pick.
	Backend string `json:"backend"`

	// Fields carries the extra form fields the device must send alongside
	// the file. The chisimba backend needs them (module name, input name);
	// the s3 backend leaves this empty.
	Fields map[string]string `json:"fields,omitempty"`
}

// Service answers upload-target requests.
type Service struct {
	backend Backend
}

// Backend is one storage implementation.
type Backend interface {
	// Target returns where a new upload should go. mediaID is the id the
	// sync protocol will later confirm by; contentType is advisory, used
	// by the s3 backend to set the object's content type.
	Target(ctx context.Context, mediaID, contentType string) (*Target, error)
}

// New builds a service over the given backend.
func New(b Backend) *Service {
	return &Service{backend: b}
}

// Target returns where a device should PUT a new upload.
//
// The id is generated by the caller (the HTTP layer), so the same id can
// serve as the object key for s3 or the client-supplied filename for
// chisimba. An empty id is a bug, caught here rather than in the store.
func (s *Service) Target(ctx context.Context, mediaID, contentType string) (*Target, error) {
	if mediaID == "" {
		return nil, errors.New("media: id is required")
	}
	if contentType == "" {
		return nil, errors.New("media: content_type is required")
	}
	if s.backend == nil {
		return nil, ErrNotConfigured
	}
	return s.backend.Target(ctx, mediaID, contentType)
}

// ---------------------------------------------------------------------------
// Chisimba backend — the default.
// ---------------------------------------------------------------------------

// Chisimba answers targets pointing at the Chisimba REST gateway's own file
// upload endpoint. The upload lands in the operator's existing file storage;
// field-service never sees the bytes.
type Chisimba struct {
	// GatewayURL is the public base of the Chisimba REST gateway, e.g.
	// "https://staff.chisimba.example.com/api/v1". No trailing slash.
	GatewayURL string
}

// NewChisimba builds the default backend.
func NewChisimba(gatewayURL string) *Chisimba {
	return &Chisimba{GatewayURL: gatewayURL}
}

// Target returns the gateway's /files endpoint.
//
// The upload is a multipart POST, so the "fields" hint tells the device what
// else to include in the form: the module name and the form field the file
// is sent under. These are the values fileapi's uploadUserFile expects.
func (c *Chisimba) Target(_ context.Context, mediaID, _ string) (*Target, error) {
	if c.GatewayURL == "" {
		return nil, ErrNotConfigured
	}
	return &Target{
		URL:       c.GatewayURL + "/files",
		Method:    "POST",
		ExpiresAt: time.Now().Add(24 * time.Hour).UTC().Format(time.RFC3339),
		MediaID:   mediaID,
		Backend:   "chisimba",
		Fields: map[string]string{
			"module":     "fileapi",
			"input_name": "upload",
		},
	}, nil
}

// ---------------------------------------------------------------------------
// S3 backend — the optional upgrade.
// ---------------------------------------------------------------------------

// S3Signer is the subset of the AWS SDK the S3 backend needs. An interface
// rather than the concrete client so the tests can substitute a fake that
// never touches the network.
type S3Signer interface {
	PresignPutObject(ctx context.Context, bucket, key, contentType string, expires time.Duration) (string, error)
}

// S3 answers targets pointing directly at an S3-compatible object store.
//
// The device PUTs the object to a presigned URL; field-service records the
// media row on the next sync pull. The bucket and prefix come from config,
// not from the request, so a client cannot choose where in the bucket its
// upload lands.
type S3 struct {
	signer S3Signer
	bucket string
	prefix string
	// TTL is how long the presigned URL stays valid. Fifteen minutes is the
	// default in most S3 tooling and is long enough for a field device to
	// finish an upload even over a slow link.
	ttl time.Duration
}

// NewS3 builds the S3 backend. The prefix is where in the bucket media is
// stored; an empty prefix is allowed and means the bucket root.
func NewS3(signer S3Signer, bucket, prefix string) *S3 {
	return &S3{
		signer: signer,
		bucket: bucket,
		prefix: prefix,
		ttl:    15 * time.Minute,
	}
}

// WithTTL overrides the default presign TTL. A longer TTL is a trade: more
// forgiving of slow networks, more time for a leaked URL to be abused.
func (s *S3) WithTTL(d time.Duration) *S3 {
	s.ttl = d
	return s
}

// Target returns a presigned PUT URL for the new media id.
func (s *S3) Target(ctx context.Context, mediaID, contentType string) (*Target, error) {
	if s.signer == nil || s.bucket == "" {
		return nil, ErrNotConfigured
	}
	url, err := s.signer.PresignPutObject(ctx, s.bucket, s.prefix+mediaID, contentType, s.ttl)
	if err != nil {
		return nil, fmt.Errorf("media: presign failed: %w", err)
	}
	return &Target{
		URL:       url,
		Method:    "PUT",
		ExpiresAt: time.Now().Add(s.ttl).UTC().Format(time.RFC3339),
		MediaID:   mediaID,
		Backend:   "s3",
	}, nil
}
